AWSTemplateFormatVersion: '2010-09-09'
Description: Basic AWS CloudFormation template to deploy a web application.

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0 # Replace with your preferred AMI ID
      KeyName: my-key-pair # Replace with your EC2 key pair name

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-static-files-bucket # Replace with a unique bucket name

Outputs:
  EC2InstancePublicIP:
    Description: The public IP address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
  S3BucketName:
    Description: The name of the S3 bucket
    Value: !Ref MyS3Bucket
